name1 =input ("enter your first name: ")
name2 =input ("enter your other name: ")
name3 =input ("enter your last name: ")
friends = []
friends.append(name1)
friends.append(name2)
friends.append(name3)
friends.reverse()
friends.insert(0,"Jr")
print(friends)